#:schema node_modules/wrangler/config-schema.json
name = "converter"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e1191bd43c2a47629e1481c84852def8" }
]
